version: 2.1

_run:
  prepare: &prepare
    name: "Preparing environment"
    command: |
      make prepare

jobs:
  checkout-code:
    machine:
      enabled: true
    steps:
      - checkout
      - persist_to_workspace:
            root: ~/project
            paths:
              - ./

  lint-php:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - woopagarme-cache-{{ checksum "composer.json" }}
      - run:
          name: Linting changed PHP files on PR
          command: |
            make lint-php
      - save_cache:
          key: woopagarme-cache-{{ checksum "composer.json" }}
          paths:
            - ./vendor

  lint-js:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - woopagarme-cache-{{ checksum "package.json" }}
      - run:
          name: Linting JS files
          command: |
            make lint-js
      - save_cache:
          key: woopagarme-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./cache

  test-e2e:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - woopagarme-cache-{{ checksum "package.json" }}
            - woopagarme-cache-{{ checksum "composer.json" }}
      - run: *prepare
      - run:
          name: Run tests e2e
          command: |
            make test-e2e
      - save_cache:
          key: woopagarme-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./cache

workflows:
  version: 2
  build:
    jobs:
      - checkout-code
      - lint-php:
          requires:
          - checkout-code
      - lint-js:
          requires:
          - checkout-code
      - test-e2e:
          requires:
          - lint-js
          - lint-php
